server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: jxc-admin
  mvc:
    view:
      prefix: /pages/
      suffix: .html


#session cache config
#shiro:
#  redis:
#  sessionLive: 30
#  sessionPrefix: shiro_redis_session:
#  cacheLive: 30
#  cachePrefix: shiro_redis_cache:
#  kickoutPrefix: hiro_redis_kickout:
