server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: jxc-admin
  mvc:
    view:
      prefix: /pages/
      suffix: .html




# Tomcat
#server:
#  tomcat:
#    uri-encoding: utf-8
#    max-threads: 1000
#    min-spare-threads: 30
#  port: 8080
#  connection-timeout: 5000
#  servlet:
#    context-path: /jxc-fast
#
#spring:
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6301
#    timeout: 6000
#    pool:
#      max-active: 8
#      max-idle: 8
#      min-idle: 0
#
#  datasource:
#    name: mysql_test
#    type: com.alibaba.druid.pool.DruidDataSource
#    #druid相关配置
#    druid:
#      #监控统计拦截的filters
#      filters: stat
#      driver-class-name: com.mysql.jdbc.Driver
#      #基本属性
#      url: jdbc:mysql://127.0.0.1:3306/jxc?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#      username: jxc
#      password: jxc.123
#      #配置初始化大小/最小/最大
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      #获取连接等待超时时间
#      max-wait: 60000
#      #间隔多久进行一次检测，检测需要关闭的空闲连接
#      time-between-eviction-runs-millis: 60000
#      #一个连接在池中最小生存的时间
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: true
#      test-on-return: false
#      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20
#
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  http:
#    encoding:
#      enabled: true
#      force: true
#      charset: UTF-8
#
#
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.hubin.domain
#  global-config:
#    db-config:
#      id-type: AUTO
#      field-strategy: NOT_NULL
#      column-like: true
#      logic-delete-value: -1
#      logic-not-delete-value: 0
#    banner: false
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    call-setters-on-nulls: true
#    jdbc-type-for-null: NULL
#
##pagehelper
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
#  returnPageInfo: check
#
#logging:
#  level:
#    com:
#      hubin:
#        factor: debug

